## AI Project UCS415 
#### Finding Popularity of Spotify Songs 
Nitansh Jain  102017025

In [81]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# import sklearn

In [82]:
spotify_df = pd.read_csv('spotify_data.csv')
spotify_df.head()

title      artist    top genre  \
0                  STARSTRUKK (feat. Katy Perry)       3OH!3    dance pop   
1                    My First Kiss (feat. Ke$ha)       3OH!3    dance pop   
2                                I Need A Dollar  Aloe Blacc     pop soul   
3  Airplanes (feat. Hayley Williams of Paramore)       B.o.B  atl hip hop   
4              Nothin' on You (feat. Bruno Mars)       B.o.B  atl hip hop   

   year       added  bpm  nrgy  dnce  dB  live  val  dur  acous  spch  \
0  2009  2022‑02‑17  140    81    61  -6    23   23  203      0     6   
1  2010  2022‑02‑17  138    89    68  -4    36   83  192      1     8   
2  2010  2022‑02‑17   95    48    84  -7     9   96  243     20     3   
3  2010  2022‑02‑17   93    87    66  -4     4   38  180     11    12   
4  2010  2022‑02‑17  104    85    69  -6     9   74  268     39     5   

   top year artist_type  pop  
0      2010         Duo   70  
1      2010         Duo   68  
2      2010        Solo   72  
3      2010        Solo   80  
4      2010        Solo   79

In [83]:
# converting artist type column values to a number [0,1,2]
print(spotify_df['artist_type'].value_counts())
spotify_df['artist_type'] = spotify_df['artist_type'].astype('category').cat.codes
print(spotify_df['artist_type'].value_counts())

Solo          748
Band/Group    169
Duo            70
Trio           13
Name: artist_type, dtype: int64
2    748
0    169
1     70
3     13
Name: artist_type, dtype: int64


In [84]:
# dropping column added and top year from dataframe
spotify_df.drop(['added', 'top year'], axis=1, inplace=True)
spotify_df.head()

title      artist    top genre  \
0                  STARSTRUKK (feat. Katy Perry)       3OH!3    dance pop   
1                    My First Kiss (feat. Ke$ha)       3OH!3    dance pop   
2                                I Need A Dollar  Aloe Blacc     pop soul   
3  Airplanes (feat. Hayley Williams of Paramore)       B.o.B  atl hip hop   
4              Nothin' on You (feat. Bruno Mars)       B.o.B  atl hip hop   

   year  bpm  nrgy  dnce  dB  live  val  dur  acous  spch  artist_type  pop  
0  2009  140    81    61  -6    23   23  203      0     6            1   70  
1  2010  138    89    68  -4    36   83  192      1     8            1   68  
2  2010   95    48    84  -7     9   96  243     20     3            2   72  
3  2010   93    87    66  -4     4   38  180     11    12            2   80  
4  2010  104    85    69  -6     9   74  268     39     5            2   79

In [85]:
# converting name of column top genre to genre
spotify_df = spotify_df.rename(columns={'top genre': 'genre', 'pop': 'popularity'})
spotify_df.head()

title      artist        genre  \
0                  STARSTRUKK (feat. Katy Perry)       3OH!3    dance pop   
1                    My First Kiss (feat. Ke$ha)       3OH!3    dance pop   
2                                I Need A Dollar  Aloe Blacc     pop soul   
3  Airplanes (feat. Hayley Williams of Paramore)       B.o.B  atl hip hop   
4              Nothin' on You (feat. Bruno Mars)       B.o.B  atl hip hop   

   year  bpm  nrgy  dnce  dB  live  val  dur  acous  spch  artist_type  \
0  2009  140    81    61  -6    23   23  203      0     6            1   
1  2010  138    89    68  -4    36   83  192      1     8            1   
2  2010   95    48    84  -7     9   96  243     20     3            2   
3  2010   93    87    66  -4     4   38  180     11    12            2   
4  2010  104    85    69  -6     9   74  268     39     5            2   

   popularity  
0          70  
1          68  
2          72  
3          80  
4          79

In [86]:
spotify_features = spotify_df.loc[:,'bpm':'popularity']
spotify_features.head()

bpm  nrgy  dnce  dB  live  val  dur  acous  spch  artist_type  popularity
0  140    81    61  -6    23   23  203      0     6            1          70
1  138    89    68  -4    36   83  192      1     8            1          68
2   95    48    84  -7     9   96  243     20     3            2          72
3   93    87    66  -4     4   38  180     11    12            2          80
4  104    85    69  -6     9   74  268     39     5            2          79

In [87]:
# splitting dataframe into dependent and independent variables
spotify_features_x = spotify_features.drop(['artist_type', 'popularity'], axis=1)
spotify_features_y = spotify_features['popularity']

In [88]:
# print(spotify_features_x.head())
spotify_features_x_np = np.asarray(spotify_features[['bpm', 'dnce', 'nrgy', 'dB', 'live', 'val', 'acous', 'spch']])
spotify_features_x_np[0:5]

# print(spotify_features_y.head())
spotify_features_y_np = np.asarray(spotify_features['popularity'])
spotify_features_y_np[0:5]

array([70, 68, 72, 80, 79])

In [89]:
from sklearn import preprocessing
spotify_features_X = preprocessing.StandardScaler().fit_transform(spotify_features_x_np)
spotify_features_Y = preprocessing.StandardScaler().fit_transform(spotify_features_y_np.reshape(-1, 1))


In [90]:
# splitting the data into training and testing sets
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(spotify_features_X, spotify_features_Y, test_size=0.2, random_state=42)

Using MultiLinear Regression

In [91]:
# importing Linear Regression model
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr

LinearRegression()

In [92]:
# fitting the model to the training data
lr.fit(x_train, y_train)
print(lr.intercept_)
print(lr.coef_)

[0.01738899]
[[ 0.00382443  0.04130218 -0.26609989  0.05570184 -0.0847165   0.07151275
   0.01970884  0.03800992]]


In [93]:
# predicting the test data
yhat_spotify_popularity_lr = lr.predict(x_test)
print(y_test[0:5])
yhat_spotify_popularity_lr[0:5]

[[0.92691132]
 [1.38127962]
 [1.15409547]
 [0.13176681]
 [0.35895095]]


array([[-0.05127081],
       [-0.27722773],
       [ 0.31350236],
       [-0.3987498 ],
       [ 0.42162124]])

In [94]:
# finding the mean squared error, root mean squared error, and R2 score
from sklearn.metrics import r2_score

print('Residual sum of squares: %.2f' % np.mean((y_test - yhat_spotify_popularity_lr) ** 2))
print('Root Mean Square Error: %.2f' % np.sqrt(np.mean((y_test - yhat_spotify_popularity_lr) ** 2)))
print('R2 score: %.2f' % r2_score(y_test, yhat_spotify_popularity_lr))


Residual sum of squares: 0.87
Root Mean Square Error: 0.93
R2 score: 0.07


Using Polynomial Regression

In [95]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn import linear_model
poly = PolynomialFeatures(degree=2) # degree of the polynomial features 
train_spotify_pop_poly = poly.fit_transform(x_train) # transforming the training data

In [96]:
clf = linear_model.LinearRegression() # create a linear regression object
clf.fit(train_spotify_pop_poly, y_train) # fitting the model to the training data
print(clf.intercept_) # printing the intercept
print(clf.coef_) # printing the coefficients

[0.03379012]
[[-2.34716946e-17 -6.25917549e-03  1.39877920e-02 -2.93603194e-01
   3.84556262e-02 -1.17963427e-01  5.23283652e-02 -3.92218350e-02
   2.64657818e-02  3.30559212e-03 -1.84249642e-02 -3.65668812e-02
  -1.42684856e-02  3.70611562e-02  7.34479175e-02 -6.69606729e-03
   2.15858281e-02 -8.88679827e-02 -6.70544790e-02  6.55198724e-02
   2.58451932e-02  3.98245501e-02 -9.31874817e-03  3.48487922e-02
  -7.04770968e-02 -3.81395510e-02  9.36141292e-03  1.34545693e-01
  -4.12288885e-02  3.67603313e-02  2.32871379e-02 -2.26893206e-02
   4.81583998e-02  7.06739021e-02 -1.23366288e-02  3.82535173e-02
  -4.86606531e-02  9.61619826e-02  8.40035860e-02 -2.73757228e-02
   6.95651926e-03 -5.91759967e-02  5.12490361e-02  6.20550423e-02
   1.78843004e-02]]


In [97]:
x_test_poly = poly.fit_transform(x_test) # transform the test data into polynomial features for the model
yhat_test_spotify_pop_poly_lr = clf.predict(x_test_poly) # predict the test data using the model

In [98]:
# finding mean square error, root mean square error, and R2 score

print('Mean Square Error: %.2f' % np.mean((y_test - yhat_test_spotify_pop_poly_lr) ** 2))
print('Root Mean Square Error: %.2f' % np.sqrt(np.mean((y_test - yhat_test_spotify_pop_poly_lr) ** 2)))
print('R2 score: %.2f' % r2_score(y_test, yhat_test_spotify_pop_poly_lr))

Mean Square Error: 0.88
Root Mean Square Error: 0.94
R2 score: 0.06
