## AI Project UCS415 
#### Finding Popularity of Spotify Songs 
Nitansh Jain  102017025

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# import sklearn

In [3]:
spotify_df = pd.read_csv('top10s.csv', encoding='latin-1')
spotify_df.head()

Unnamed: 0                 title      artist        top genre  year  bpm  \
0           1      Hey, Soul Sister       Train       neo mellow  2010   97   
1           2  Love The Way You Lie      Eminem  detroit hip hop  2010   87   
2           3               TiK ToK       Kesha        dance pop  2010  120   
3           4           Bad Romance   Lady Gaga        dance pop  2010  119   
4           5  Just the Way You Are  Bruno Mars              pop  2010  109   

   nrgy  dnce  dB  live  val  dur  acous  spch  pop  
0    89    67  -4     8   80  217     19     4   83  
1    93    75  -5    52   64  263     24    23   82  
2    84    76  -3    29   71  200     10    14   80  
3    92    70  -4     8   71  295      0     4   79  
4    84    64  -5     9   43  221      2     4   78

In [4]:
# checking if any null values are present
print(spotify_df.isnull().sum())

Unnamed: 0    0
title         0
artist        0
top genre     0
year          0
bpm           0
nrgy          0
dnce          0
dB            0
live          0
val           0
dur           0
acous         0
spch          0
pop           0
dtype: int64


In [5]:
spotify_df.dtypes

Unnamed: 0     int64
title         object
artist        object
top genre     object
year           int64
bpm            int64
nrgy           int64
dnce           int64
dB             int64
live           int64
val            int64
dur            int64
acous          int64
spch           int64
pop            int64
dtype: object

In [6]:
# converting name of column top genre to genre
spotify_df = spotify_df.rename(columns={'top genre': 'genre', 'pop': 'popularity'})
spotify_df.head()

Unnamed: 0                 title      artist            genre  year  bpm  \
0           1      Hey, Soul Sister       Train       neo mellow  2010   97   
1           2  Love The Way You Lie      Eminem  detroit hip hop  2010   87   
2           3               TiK ToK       Kesha        dance pop  2010  120   
3           4           Bad Romance   Lady Gaga        dance pop  2010  119   
4           5  Just the Way You Are  Bruno Mars              pop  2010  109   

   nrgy  dnce  dB  live  val  dur  acous  spch  popularity  
0    89    67  -4     8   80  217     19     4          83  
1    93    75  -5    52   64  263     24    23          82  
2    84    76  -3    29   71  200     10    14          80  
3    92    70  -4     8   71  295      0     4          79  
4    84    64  -5     9   43  221      2     4          78

In [7]:
spotify_df.drop_duplicates(subset='title',inplace=True)

In [8]:
# getting columns from spotify_df from bpm to artist_type via loc
spotify_features = spotify_df

# dropping column added and top year from dataframe
spotify_features.drop(['title', 'Unnamed: 0'], axis=1, inplace=True)
spotify_df.head()

artist            genre  year  bpm  nrgy  dnce  dB  live  val  dur  \
0       Train       neo mellow  2010   97    89    67  -4     8   80  217   
1      Eminem  detroit hip hop  2010   87    93    75  -5    52   64  263   
2       Kesha        dance pop  2010  120    84    76  -3    29   71  200   
3   Lady Gaga        dance pop  2010  119    92    70  -4     8   71  295   
4  Bruno Mars              pop  2010  109    84    64  -5     9   43  221   

   acous  spch  popularity  
0     19     4          83  
1     24    23          82  
2     10    14          80  
3      0     4          79  
4      2     4          78

In [9]:
from sklearn import preprocessing
le_artist = preprocessing.LabelEncoder()
le_artist.fit(spotify_features['artist'])
spotify_features['artist'] = le_artist.transform(spotify_features['artist'])

le_genre = preprocessing.LabelEncoder()
le_genre.fit(spotify_features['genre'])
spotify_features['genre'] = le_genre.transform(spotify_features['genre'])


In [10]:
# splitting dataframe into dependent and independent variables
spotify_features_x = spotify_features.drop(['popularity'], axis=1)
spotify_features_y = spotify_features['popularity']

In [11]:
# print(spotify_features_x.head())
spotify_features_x_np = np.asarray(spotify_features_x)
spotify_features_x_np[0:5]

# print(spotify_features_y.head())
spotify_features_y_np = np.asarray(spotify_features_y)
spotify_features_y_np[0:5]

array([83, 82, 80, 79, 78])

In [12]:
from sklearn import preprocessing
spotify_features_X = preprocessing.MinMaxScaler().fit_transform(spotify_features_x_np)
spotify_features_Y = preprocessing.MinMaxScaler().fit_transform(spotify_features_y_np.reshape(-1, 1))


In [13]:
# splitting the data into training and testing sets
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(spotify_features_X, spotify_features_Y, test_size=0.25, random_state=42)

Using MultiLinear Regression

In [14]:
# importing Linear Regression model
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr

LinearRegression()

In [15]:
# fitting the model to the training data
lr.fit(x_train, y_train)
print(lr.intercept_)
print(lr.coef_)

[-0.05374289]
[[ 0.00323168  0.03309824  0.13037005 -0.04768063 -0.17249056 -0.00627645
   0.83607596 -0.02199541  0.03556245  0.01735019 -0.04749727 -0.0259688 ]]


In [16]:
# predicting the test data
yhat_spotify_popularity_lr = lr.predict(x_test)


In [17]:
# finding the mean squared error, root mean squared error, and R2 score
from sklearn.metrics import r2_score

print('Residual sum of squares: %.2f' % np.mean((y_test - yhat_spotify_popularity_lr) ** 2))
print('Root Mean Square Error: %.2f' % np.sqrt(np.mean((y_test - yhat_spotify_popularity_lr) ** 2)))
print('R2 score: %.2f' % r2_score(y_test, yhat_spotify_popularity_lr))


Residual sum of squares: 0.02
Root Mean Square Error: 0.13
R2 score: 0.05


In [18]:
print(yhat_spotify_popularity_lr[0:5])
print(y_test[0:5])

[[0.66913846]
 [0.64574057]
 [0.64593183]
 [0.69850049]
 [0.68669034]]
[[0.72727273]
 [0.36363636]
 [0.54545455]
 [0.66666667]
 [0.75757576]]


Using Polynomial Regression

In [19]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn import linear_model
poly = PolynomialFeatures(degree=2) # degree of the polynomial features 
train_spotify_pop_poly = poly.fit_transform(x_train) # transforming the training data

In [20]:
clf = linear_model.LinearRegression() # create a linear regression object
clf.fit(train_spotify_pop_poly, y_train) # fitting the model to the training data
# print(clf.intercept_) # printing the intercept
# print(clf.coef_) # printing the coefficients

LinearRegression()

In [21]:
x_test_poly = poly.fit_transform(x_test) # transform the test data into polynomial features for the model
yhat_test_spotify_pop_poly_lr = clf.predict(x_test_poly) # predict the test data using the model

In [22]:
# finding mean square error, root mean square error, and R2 score

print('Mean Square Error: %.2f' % np.mean((y_test - yhat_test_spotify_pop_poly_lr) ** 2))
print('Root Mean Square Error: %.2f' % np.sqrt(np.mean((y_test - yhat_test_spotify_pop_poly_lr) ** 2)))
print('R2 score: %.2f' % r2_score(y_test, yhat_test_spotify_pop_poly_lr))

Mean Square Error: 0.02
Root Mean Square Error: 0.16
R2 score: -0.29
